### ISSUE TITLE
Rarity not working

### ISSUE THREAD

**Issue by sadun619** [bolshoytoster/hashlips_art_engine#1]
### Checklist

- [X] I have read [COMMON_ISSUES.md](https://github.com/HashLips/hashlips_art_engine/blob/main/COMMON_ISSUES.md)
- [X] I have [searched existing issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue)

### Description

i use this for generate 10k collection as 4 phases (2500x4).

but cannot see rarity. showing up below error.

Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blue to Yellow #88.png': undefined/Blue to Yellow #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Fade to Mint #88.png': undefined/Fade to Mint #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Fade to Orange #36.png': undefined/Fade to Orange #36.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Blue #113.png': undefined/Light Blue #113.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Green  #100.png': undefined/Light Green  #100.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Grey #100.png': undefined/Light Grey #100.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Teal #113.png': undefined/Light Teal #113.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Yellow #100.png': undefined/Light Yellow #100.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Mixed Pastels #88.png': undefined/Mixed Pastels #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Pink to Mint #63.jpg': undefined/Pink to Mint #63.jpg
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Purple to Pink #63.png': undefined/Purple to Pink #63.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Rainbow of Life #88.png': undefined/Rainbow of Life #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Reflective Blue  #100.jpg': undefined/Reflective Blue  #100.jpg
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Sunshine  #88.png': undefined/Sunshine  #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond #188.png': undefined/Almond #188.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Chestnut #125.png': undefined/Chestnut #125.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Espresso #188.png': undefined/Espresso #188.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Honey #250.png': undefined/Honey #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Ivory #500.png': undefined/Ivory #500.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black #250.png': undefined/Black #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Charcoal #250.png': undefined/Charcoal #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Blue #250.png': undefined/Light Blue #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Gray #250.png': undefined/Light Gray #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red #250.png': undefined/Red #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blue Light & Blue #250.png': undefined/Blue Light & Blue #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Green & Brown #250.png': undefined/Green & Brown #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Blue & Blue #250.png': undefined/Light Blue & Blue #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Purple & White #250.png': undefined/Purple & White #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/White & Blue #250.png': undefined/White & Blue #250.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Big Black #200.png': undefined/Big Black #200.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Big Blue #200.png': undefined/Big Blue #200.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Big Brown #225.png': undefined/Big Brown #225.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Big Gray #200.png': undefined/Big Gray #200.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Big Green #200.png': undefined/Big Green #200.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Big Hazel #225.png': undefined/Big Hazel #225.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Aviator Shades #188.png': undefined/Aviator Shades #188.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blue Shades #188.png': undefined/Blue Shades #188.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Metal Rimmed Shades #125.png': undefined/Metal Rimmed Shades #125.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Purple Shades #188.png': undefined/Purple Shades #188.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Round Potters Shades #125.png': undefined/Round Potters Shades #125.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Wayfarer Black #125.png': undefined/Wayfarer Black #125.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Wayfarer Blue #125.png': undefined/Wayfarer Blue #125.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Yellow Shades #125.png': undefined/Yellow Shades #125.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 10 #15.png': undefined/Black Hairstyle 10 #15.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 6 #15.png': undefined/Black Hairstyle 6 #15.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 7 #15.png': undefined/Black Hairstyle 7 #15.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 8 #15.png': undefined/Black Hairstyle 8 #15.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 9 #18.png': undefined/Black Hairstyle 9 #18.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 6 #18.png': undefined/Blond Hairstyle 6 #18.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 7 #15.png': undefined/Blond Hairstyle 7 #15.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 8 #18.png': undefined/Blond Hairstyle 8 #18.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 9 #15.png': undefined/Blond Hairstyle 9 #15.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 5 #15.png': undefined/Brown Hairstyle 5 #15.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 6 #18.png': undefined/Brown Hairstyle 6 #18.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 7 #18.png': undefined/Brown Hairstyle 7 #18.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 8 #18.png': undefined/Brown Hairstyle 8 #18.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle Hairstyle 9 #15.png': undefined/Brown Hairstyle Hairstyle 9 #15.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 2 #13.png': undefined/Red Hairstyle 2 #13.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 3 #13.png': undefined/Red Hairstyle 3 #13.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Alpha Generation #13.png': undefined/Alpha Generation #13.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 7 #60.png': undefined/Black Hairstyle 7 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 8 #60.png': undefined/Black Hairstyle 8 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 9 #70.png': undefined/Black Hairstyle 9 #70.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 6 #70.png': undefined/Blond Hairstyle 6 #70.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 7 #60.png': undefined/Blond Hairstyle 7 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 9 #60.png': undefined/Blond Hairstyle 9 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 5 #60.png': undefined/Brown Hairstyle 5 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 6 #70.png': undefined/Brown Hairstyle 6 #70.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 7 #70.png': undefined/Brown Hairstyle 7 #70.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Baseball #150.png': undefined/Baseball #150.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Beanie Skul #150.png': undefined/Beanie Skul #150.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Beret #82.png': undefined/Beret #82.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Newsboy #52.png': undefined/Newsboy #52.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Pork Pie #27.png': undefined/Pork Pie #27.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 8 #70.png': undefined/Brown Hairstyle 8 #70.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 9 #60.png': undefined/Brown Hairstyle 9 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 2 #50.png': undefined/Red Hairstyle 2 #50.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 3 #50.png': undefined/Red Hairstyle 3 #50.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Bucket #100.png': undefined/Bucket #100.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Cowboy #125.png': undefined/Cowboy #125.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Fedora #125.png': undefined/Fedora #125.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 6 #60.png': undefined/Black Hairstyle 6 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 8 #70.png': undefined/Blond Hairstyle 8 #70.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Beret #43.png': undefined/Beret #43.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Newsboy #43.png': undefined/Newsboy #43.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Pork Pie #43.png': undefined/Pork Pie #43.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 10 #60.png': undefined/Black Hairstyle 10 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Newsboy #30.png': undefined/Newsboy #30.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Pork Pie #30.png': undefined/Pork Pie #30.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond #56.png': undefined/Almond #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Chestnut #38.png': undefined/Chestnut #38.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Espresso #56.png': undefined/Espresso #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Honey #75.png': undefined/Honey #75.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Ivory #150.png': undefined/Ivory #150.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black #56.png': undefined/Black #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Blue #60.png': undefined/Light Blue #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Burgundy #56.png': undefined/Light Burgundy #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Light Green #68.png': undefined/Light Green #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Pink #68.png': undefined/Pink #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Purple #68.png': undefined/Purple #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blue & White #68.png': undefined/Blue & White #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red & White #56.png': undefined/Red & White #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red & yellow #68.png': undefined/Red & yellow #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/White & Blue 60.png': undefined/White & Blue 60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Yellow & Brown #56.png': undefined/Yellow & Brown #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Oval Black #60.png': undefined/Oval Black #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Oval Blue #68.png': undefined/Oval Blue #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Oval Brown#60.png': undefined/Oval Brown#60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Oval Green #68.png': undefined/Oval Green #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Oval Grey #60.png': undefined/Oval Grey #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Oval Hazel #60.png': undefined/Oval Hazel #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Aviator Shades #56.png': undefined/Aviator Shades #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blue Shades #56.png': undefined/Blue Shades #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Metal Rimmed #38.png': undefined/Metal Rimmed #38.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Purple Shades #56.png': undefined/Purple Shades #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Round Potters #38.png': undefined/Round Potters #38.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Wayfarer Black #38.png': undefined/Wayfarer Black #38.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Wayfarer Blue #38.png': undefined/Wayfarer Blue #38.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Yellow Shades #38.png': undefined/Yellow Shades #38.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Ash Silver Hairstyle 1 #56.png': undefined/Ash Silver Hairstyle 1 #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 1 #60.png': undefined/Black Hairstyle 1 #60.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 1 #68.png': undefined/Brown Hairstyle 1 #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Burgundy Hairstyle 1 #68.png': undefined/Burgundy Hairstyle 1 #68.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 1 #56.png': undefined/Red Hairstyle 1 #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Baseball #58.png': undefined/Baseball #58.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Beanie Skull #69.png': undefined/Beanie Skull #69.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Beret #58.png': undefined/Beret #58.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Newsboy #69.png': undefined/Newsboy #69.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Pork Pie #46.png': undefined/Pork Pie #46.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond #131.png': undefined/Almond #131.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Chestnut #88.png': undefined/Chestnut #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Espresso #132.png': undefined/Espresso #132.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Honey #175.png': undefined/Honey #175.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Ivory #350.png': undefined/Ivory #350.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black #149.png': undefined/Black #149.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blue #193.png': undefined/Blue #193.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Green #193.png': undefined/Green #193.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Purple #149.png': undefined/Purple #149.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Yellow #193.png': undefined/Yellow #193.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Pink & Teal #175.png': undefined/Pink & Teal #175.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red & Black #219.png': undefined/Red & Black #219.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Teal & Orange #131.png': undefined/Teal & Orange #131.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/White & Blue #175.png': undefined/White & Blue #175.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/White & Brown #175.png': undefined/White & Brown #175.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond Black #140.png': undefined/Almond Black #140.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond Blue #140.png': undefined/Almond Blue #140.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond Brown #158.png': undefined/Almond Brown #158.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond Green #140.png': undefined/Almond Green #140.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond Grey #140.png': undefined/Almond Grey #140.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Almond Hazel #156.png': undefined/Almond Hazel #156.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Aviator Shades #131.png': undefined/Aviator Shades #131.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blue Shades #131.png': undefined/Blue Shades #131.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Metal Rimmed #88.png': undefined/Metal Rimmed #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Purple Shades #131.png': undefined/Purple Shades #131.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Round Potters #88.png': undefined/Round Potters #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Wayfarer Black #88.png': undefined/Wayfarer Black #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Wayfarer Blue #88.png': undefined/Wayfarer Blue #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Yellow Shades #88.png': undefined/Yellow Shades #88.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 2 #12.png': undefined/Black Hairstyle 2 #12.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 3 #12.png': undefined/Black Hairstyle 3 #12.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 4 #61.png': undefined/Black Hairstyle 4 #61.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 5 #61.png': undefined/Black Hairstyle 5 #61.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 2 #12.png': undefined/Blond Hairstyle 2 #12.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 3 #14.png': undefined/Blond Hairstyle 3 #14.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 4 #12.png': undefined/Blond Hairstyle 4 #12.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 5 #61.png': undefined/Blond Hairstyle 5 #61.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 2 #14.png': undefined/Brown Hairstyle 2 #14.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 3 #14.png': undefined/Brown Hairstyle 3 #14.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 4 #61.png': undefined/Brown Hairstyle 4 #61.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 4 #61.png': undefined/Red Hairstyle 4 #61.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 5 #35.png': undefined/Red Hairstyle 5 #35.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 6 #7.png': undefined/Red Hairstyle 6 #7.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 7 #7.png': undefined/Red Hairstyle 7 #7.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 8 #35.png': undefined/Red Hairstyle 8 #35.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Black Hairstyle 2 #77.png': undefined/Black Hairstyle 2 #77.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 3 #87.png': undefined/Blond Hairstyle 3 #87.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Blond Hairstyle 4 #49.png': undefined/Blond Hairstyle 4 #49.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Brown Hairstyle 2 #56.png': undefined/Brown Hairstyle 2 #56.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairstyle 5 #28.png': undefined/Red Hairstyle 5 #28.png
tyle 3 #87.png': undefined/Brown Hairstyle 3 #87.png                                                  le 7 #28.png': undefined/Red Hairstyle 7 #28.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Red Hairsty8.png': undefined/Newsboy #158.pngle 6 #43.png': undefined/Red Hairstyle 6 #43.png                                                      08.png': undefined/Pork Pie #108.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Baseball #1tyle 3 #76.png': undefined/Black Hairstyle 3 #76.png34.png': undefined/Baseball #134.png                                                                  tyle 2 #76.png': undefined/Blond Hairstyle 2 #76.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Beanie Skultyle 3 #87.png': undefined/Brown Hairstyle 3 #87.png  #161.png': undefined/Beanie Skul  #161.png                                                          le 6 #43.png': undefined/Red Hairstyle 6 #43.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Beret #135.34.png': undefined/Baseball #134.pngpng': undefined/Beret #135.png                                                                          #161.png': undefined/Beanie Skul  #161.png
Error: ENOENT, No such file or directory 'E:\cus\hashlips_art_engine-main/layers/undefined/Newsboy #4.png': undefined/Beret #135.pngpng': undefined/Newsboy #4.png                                                                        png': undefined/Newsboy #4.png
Trait type: Background

Trait type: Skin

Trait type: Cape

Trait type: Cloths

Trait type: Eyes

Trait type: Eyewear

Trait type: Hair

Trait type: Alpha Generation Logo

Trait type: Hat

### Steps to reproduce

i used display name to layer configuration.

            { name: "Boy Background", options:{displayName:"Background"} },
            { name: "Boy Skin", options:{displayName:"Skin"} },
            { name: "Boy Cape", options: {displayName:"Cape"} },
            { name: "Boy Cloth", options: {displayName:"Cloths"} },
            { name: "Boy Eye", options: {displayName:"Eyes"} },
            { name: "Boy Eyewear", options: {displayName:"Eyewear"} },
            { name: "Boy Hair", options: {displayName:"Hair"} },

### Environment

OS Version (`uname -a` on unix, `systeminfo` on windows): win 10
Node.js version (`node -v`): 17.4

**Comment by bolshoytoster** [comment]
@sadun619 sorry, I think it shoukd be working now.

**Comment by sadun619** [comment]
@bolshoytoster Checked. now it's working. thank you
