### ISSUE TITLE
showing attribute repeatedly in rarity without values

### ISSUE THREAD

**Issue by sadun619** [bolshoytoster/hashlips_art_engine#18]
### Checklist

- [X] I have read [COMMON_ISSUES.md](https://github.com/HashLips/hashlips_art_engine/blob/main/COMMON_ISSUES.md)
- [X] I have [searched existing issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue)

### Description

when generate rarity it shows attribute over and over without values. Eg. if have 5 layers, rarity showing with generated values for 1 st  layer and other 4 layers without generated values. it happens to each layer and showing rarity 25 times.

![Screenshot (204)](https://user-images.githubusercontent.com/6003462/210787335-da2d018b-6cad-446e-8c26-0c839fecf0b0.png)

this is my layer configuration.

![Screenshot (205)](https://user-images.githubusercontent.com/6003462/210787431-a0ffc734-8d12-4a8f-a6d1-35ce83fa1991.png)

it shows unnecessary attributes for all traits, after each layer, like highlighted in above image.

if have 5 layers and 5 traits for each layer. (Total 25 layers), rarity show 25 times for each trait types. (5 with values and 20 without values for one trait type, total have 125. unnecessary 100 and 25 with values)

### Environment

OS Version (`uname -a` on unix, `systeminfo` on windows):
Node.js version (`node -v`):

**Comment by bolshoytoster** [comment]
@sadun619 if you generated a collection then added more images, those extra images would show up since that's how the script gets the list of images.

If you don't want them to show up you could change lines ~64-70:
https://github.com/bolshoytoster/hashlips_art_engine/blob/16a9d9c2581ff78f13db064d1e830a0e5d8d2637/utils/rarity.js#L64-L70

to
```js
    if (rarityData[layer][attribute].occurrence == 0) {
        delete rarityData[layer][attribute];
    } else {
      // get chance
      let chance =
        ((rarityData[layer][attribute].occurrence / editionSize) * 100).toFixed(2);

      // show two decimal places in percent
      rarityData[layer][attribute].occurrence =
        `${rarityData[layer][attribute].occurrence} in ${editionSize} editions (${chance} %)`;
    }
```

**Comment by sadun619** [comment]
> @sadun619 if you generated a collection then added more images, those extra images would show up since that's how the script gets the list of images.
> 
> If you don't want them to show up you could change lines ~64-70:
> 
> https://github.com/bolshoytoster/hashlips_art_engine/blob/16a9d9c2581ff78f13db064d1e830a0e5d8d2637/utils/rarity.js#L64-L70
> 
> to
> 
> ```js
>     if (rarityData[layer][attribute].occurrence == 0) {
>         delete rarityData[layer][attribute];
>     } else {
>       // get chance
>       let chance =
>         ((rarityData[layer][attribute].occurrence / editionSize) * 100).toFixed(2);
> 
>       // show two decimal places in percent
>       rarityData[layer][attribute].occurrence =
>         `${rarityData[layer][attribute].occurrence} in ${editionSize} editions (${chance} %)`;
>     }
> ```

it's working. thank you.
