### ISSUE TITLE
startEditionFrom: not working

### ISSUE THREAD

**Issue by kingchenc** [bolshoytoster/hashlips_art_engine#3]
### Checklist

- [X] I have read [COMMON_ISSUES.md](https://github.com/HashLips/hashlips_art_engine/blob/main/COMMON_ISSUES.md)
- [X] I have [searched existing issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue)

### Description

Hi,

startEditionFrom: 0 does not work.

```
const layerConfigurations = [
  {
    growEditionSizeTo: 250,
    startEditionFrom: 0,
    layersOrder: [
      { name: "Background" },
      { name: "Eyeball" },
      { name: "Eye color" },
      { name: "Iris" },
      { name: "Shine" },
      { name: "Bottom lid" },
      { name: "Top lid" },
    ],
  },
];
```

Example Conf with startEditionFrom 0, but it starts at 1.png

how to solve this? 

thank you

### Environment

OS Version (`uname -a` on unix, `systeminfo` on windows):
Node.js version (`node -v`):

**Comment by bolshoytoster** [comment]
@kingchenc I've fixed it now, you can do it yourself by changing `src/main.js` ~line 440:
https://github.com/bolshoytoster/hashlips_art_engine/blob/733520e66a115c78447c7297173ac08c3ed864b5/src/main.js#L439-L441

to
```js
    if (network != NETWORK.sol && layerconfiguration.startEditionFrom != undefined) {
```

**Comment by kingchenc** [comment]
@bolshoytoster Thanks for the reply, i changed the following Code, but still starts at 1 :/

**Comment by bolshoytoster** [comment]
@kingchenc did you definetely save the `src/main.js` file?

**Comment by kingchenc** [comment]
@bolshoytoster Yes i saved it ;)

Created new one, still same output.

Created edition: 250, with DNA: 8ca27521450312a4888795948c7a23c1698d34db
Saved edition: 2
Saved edition: 1
Saved edition: 4

**Comment by bolshoytoster** [comment]
@kingchenc it works for me, could you download the latest version of the repo.

**Comment by kingchenc** [comment]
@bolshoytoster Looks very strange...
Downloaded your latest Repo with the StartEditionFrom Fix,

Added this to the config: (and yes i saved)

```
const layerConfigurations = [
  {
    growEditionSizeTo: 5,
    StartEditionFrom: 0,
```

But still the same output

Created edition: 1, with DNA: 62d9e30798ab3cbe6a6366f26ac17e68cc322cc1
Created edition: 2, with DNA: 92d6f5150aead5820b188bc56464b5e1961b160b
Created edition: 3, with DNA: 594219bfa83c650c4811a0db3ad0c2ec03f5bdf2
Created edition: 4, with DNA: 9bb9813d780bc66544bbd1552711b069b03ebacd
Created edition: 5, with DNA: ab40c455bf9dec78b50909d414d873442f5dd4f7
Saved edition: 1
Saved edition: 2
Saved edition: 3
Saved edition: 4
Saved edition: 5

**Comment by bolshoytoster** [comment]
@kingchenc I just realised your `StartEditionFrom` should start with a lowercase `s`.

**Comment by kingchenc** [comment]
> @kingchenc I just realised your `StartEditionFrom` should start with a lowercase `s`.

Thanks that was it, seems simple.... Thank you <3
